# Generated by Django 4.1.7 on 2023-03-04 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articleimages_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'Објава', 'verbose_name_plural': 'Објави'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Слика за објава', 'verbose_name_plural': 'Слики за објава'},
        ),
        migrations.AlterModelOptions(
            name='contactformmessage',
            options={'verbose_name': 'Порака', 'verbose_name_plural': 'Пораки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Вработен', 'verbose_name_plural': 'Вработени'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Категорија за галерија', 'verbose_name_plural': 'Категории за галерија'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Слика за галерија', 'verbose_name_plural': 'Слики за галерија'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слајдер', 'verbose_name_plural': 'Слајдери'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Слика за слајдер', 'verbose_name_plural': 'Слики за слајдер'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='name_mk',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='name_sq',
        ),
        migrations.AddField(
            model_name='contactformmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Наслов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_mk',
            field=models.CharField(max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_sq',
            field=models.CharField(max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_mk',
            field=models.TextField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_sq',
            field=models.TextField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Креирано на'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_mk',
            field=models.CharField(max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_sq',
            field=models.CharField(max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.article', verbose_name='Објава'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Слика'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Емаил'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Име и презиме'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Емаил'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Вработен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Вработен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_mk',
            field=models.CharField(max_length=50, null=True, verbose_name='Вработен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_sq',
            field=models.CharField(max_length=50, null=True, verbose_name='Вработен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Титула'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Титула'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_mk',
            field=models.CharField(max_length=20, null=True, verbose_name='Титула'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title_sq',
            field=models.CharField(max_length=20, null=True, verbose_name='Титула'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_mk',
            field=models.CharField(max_length=50, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_sq',
            field=models.CharField(max_length=50, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='main.gallerycategory', verbose_name='Категорија'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Слика'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.SlugField(verbose_name='Позиција'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Слика'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Редослед'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.slider', verbose_name='Слајдер'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='employees',
            field=models.ManyToManyField(related_name='subjects', to='main.employee', verbose_name='Вработени'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_mk',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_sq',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
    ]
