# Generated by Django 4.1.7 on 2023-03-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_options_alter_articleimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_slug',
            field=models.SlugField(default='', verbose_name='Име слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='position_slug',
            field=models.SlugField(default='', verbose_name='Позиција слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Позиција'),
        ),
    ]
