# Generated by Django 4.1.7 on 2023-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_gallerycategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_slug',
            field=models.SlugField(unique=True, verbose_name='Име слаг'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position_slug',
            field=models.SlugField(unique=True, verbose_name='Позиција слаг'),
        ),
    ]
