# Generated by Django 4.1.7 on 2023-03-10 08:04

from django.db import migrations, models

def forward_func(apps, schema_editor):
    Slider = apps.get_model('main', 'Slider')
    Slider.objects.create(position='Main page', position_slug='index-slider')

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gallerycategory_name_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
