# Generated by Django 4.1.7 on 2023-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_index_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст'),
        ),
    ]
