# Generated by Django 4.1.7 on 2023-03-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sliderimage_text_en_sliderimage_text_mk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='text_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='text_mk',
            new_name='title_mk',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='text_sq',
            new_name='title_sq',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Редослед'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.article', verbose_name='Слајдер'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_mk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_sq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Наслов'),
        ),
    ]
