# Generated by Django 4.1.7 on 2023-03-16 06:54

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_articleimage_title_en_articleimage_title_mk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=django_quill.fields.QuillField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_mk',
            field=django_quill.fields.QuillField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_sq',
            field=django_quill.fields.QuillField(null=True, verbose_name='Содржина'),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Содржина'),
        ),
    ]
