# Generated by Django 4.1.7 on 2023-03-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_article_content_alter_article_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Име')),
                ('name_slug', models.SlugField(max_length=20, unique=True, verbose_name='Име слаг')),
            ],
            options={
                'verbose_name': 'Категорија на прилози',
                'verbose_name_plural': 'Категории на прилози',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Име')),
                ('file', models.FileField(upload_to='', verbose_name='Прилог')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attachmentcategory')),
            ],
            options={
                'verbose_name': 'Прилог',
                'verbose_name_plural': 'Прилози',
            },
        ),
    ]
