# Generated by Django 4.1.7 on 2023-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_attachmentcategory_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name_mk',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='name_sq',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AddField(
            model_name='attachmentcategory',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AddField(
            model_name='attachmentcategory',
            name='name_mk',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
        migrations.AddField(
            model_name='attachmentcategory',
            name='name_sq',
            field=models.CharField(max_length=20, null=True, verbose_name='Име'),
        ),
    ]
