# Generated by Django 4.1.7 on 2023-03-24 10:07

from django.db import migrations, models

def forward_func(apps, schema_editor):
    AttachmentCategory = apps.get_model('main', 'AttachmentCategory')
    AttachmentCategory.objects.bulk_create([
        AttachmentCategory(
            name='Самоевалуација',
            name_mk='Самоевалуација',
            name_en='Self-evaluation',
            name_sq='Vetëvlerësimi',
            name_slug='self-evaluation'
        ),
        AttachmentCategory(
            name='Завршна сметка',
            name_mk='Завршна сметка',
            name_en='Final bill',
            name_sq='Fatura përfundimtare',
            name_slug='final-bill'
        ),
        AttachmentCategory(
            name='Јавна набавка',
            name_mk='Јавна набавка',
            name_en='Public acquisition',
            name_sq='Blerjet publike',
            name_slug='public-acquisition'
        ),
        AttachmentCategory(
            name='Брошура за родители',
            name_mk='Брошура за родители',
            name_en='Brochure for parents',
            name_sq='Broshurë për prindërit',
            name_slug='brochure-for-parents'
        ),
        AttachmentCategory(
            name='Документи',
            name_mk='Документи',
            name_en='Documents',
            name_sq='Dokumentet',
            name_slug='documents'
        ),
    ])

def reverse_func(apps, schema_editor):
    AttachmentCategory = apps.get_model('main', 'AttachmentCategory')
    AttachmentCategory.objects.filter(name_slug__in=(
        'self-evaluation', 
        'final-bill', 
        'public-acquisition',
        'documents',
        'brochure-for-parents',
    )).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_contactformmessage_content'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
