# Generated by Django 4.1.7 on 2023-03-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_attachment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_mk',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Име слаг'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_sq',
            field=models.CharField(max_length=100, null=True, verbose_name='Име'),
        ),
    ]
