# Generated by Django 4.1.7 on 2023-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_attachment_name_alter_attachment_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Име и презиме'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Име и презиме'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_mk',
            field=models.CharField(max_length=50, null=True, verbose_name='Име и презиме'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_sq',
            field=models.CharField(max_length=50, null=True, verbose_name='Име и презиме'),
        ),
    ]
