# Generated by Django 4.1.7 on 2023-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_employee_full_name_alter_employee_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='hello.jpg', upload_to='', verbose_name='Слика'),
            preserve_default=False,
        ),
    ]
