# Generated by Django 4.1.7 on 2023-03-24 10:07

from django.db import migrations, models

def forward_func(apps, schema_editor):
    AttachmentCategory = apps.get_model('main', 'AttachmentCategory')
    AttachmentCategory.objects.bulk_create([
        AttachmentCategory(
            name='Државна матура',
            name_mk='Државна матура',
            name_en='Matura exam',
            name_sq='Diplomimi shtetëror',
            name_slug='matura-exam'
        ),
        AttachmentCategory(
            name='Завршен испит',
            name_mk='Завршен испит',
            name_en='Graduation exam',
            name_sq='Provimi i diplomimit',
            name_slug='graduation-exam'
        ),
        AttachmentCategory(
            name='Проектна задача',
            name_mk='Проектна задача',
            name_en='Graduation project',
            name_sq='Projekti i diplomimit',
            name_slug='graduation-project'
        ),
        AttachmentCategory(
            name='Испитни прашања',
            name_mk='Испитни прашања',
            name_en='Exam questions',
            name_sq='Pyetjet e provimit',
            name_slug='exam-questions'
        ),
    ])

def reverse_func(apps, schema_editor):
    AttachmentCategory = apps.get_model('main', 'AttachmentCategory')
    AttachmentCategory.objects.filter(name_slug__in=(
        'matura-exam',
        'graduation-exam',
        'graduation-project',
        'exam-questions'
    )).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_employee_image'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
