# Generated by Django 4.1.7 on 2023-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_subject_employees_employee_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_mk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title_sq',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наслов'),
        ),
    ]
