# Generated by Django 4.1.7 on 2023-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_galleryimage_title_alter_galleryimage_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='main.subject', verbose_name='Предмети'),
        ),
    ]
