# Generated by Django 4.1.7 on 2023-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_employee_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_mk',
            field=models.CharField(max_length=200, null=True, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='attachmentcategory',
            name='name_sq',
            field=models.CharField(max_length=200, null=True, verbose_name='Име'),
        ),
    ]
